// Generated by CoffeeScript 2.1.1
(function() {
  var a, age, b, doit, friends, name;

  name = "prafful";

  age = 30;

  console.log(name);

  console.log(age);

  doit = true;

  console.log(doit);

  friends = ["rehman", "ramesh", "manoj"]

  console.log(friends);

  //below varibale will throw undefined error.
  //whoami
  //console.log whoami
  /*
  This is multiline commend in coffeescript.
  Line 2
  Line 3
  */
  a = 21;

  b = 20;

  console.log(a + b);

  console.log(a - b);

  console.log(a * b);

  console.log(a % b);

}).call(this);
