// Generated by CoffeeScript 2.1.1
(function() {
  var Academy, a;

  Academy = (function() {
    var training;

    class Academy {
      constructor(training) {
        this.training = training;
      }

    };

    training = "";

    return Academy;

  }).call(this);

  a = new Academy("Cordova");

  console.log(a.training);

}).call(this);
