// Generated by CoffeeScript 2.1.1
(function() {
  var choice, communities_choice, community_choice, friend, friends, i, item, key, len, value;

  friends = ["rehman", "ramesh", "manoj"];

  for (i = 0, len = friends.length; i < len; i++) {
    friend = friends[i];
    console.log('friend name: ' + friend);
  }

  community_choice = {
    season: 'winter',
    picnic: 'beach',
    sport: 'football',
    movie: 'mystery'
  };

  for (item in community_choice) {
    choice = community_choice[item];
    console.log(item + ' : ' + choice);
  }

  communities_choice = [
    {
      season: 'winter',
      picnic: 'beach',
      sport: 'football',
      movie: 'mystery'
    },
    {
      season: 'summer',
      picnic: 'hill station',
      sport: 'snow boarding',
      movie: 'comedy'
    },
    {
      season: 'monsoon',
      picnic: 'forest',
      sport: 'swimming',
      movie: 'adventure'
    }
  ];

  for (key in communities_choice) {
    value = communities_choice[key];
    console.log(key + "::" + value.season);
  }

}).call(this);
