// Generated by CoffeeScript 2.1.1
(function() {
  //define a class
  var Add, child, childClass;

  Add = (function() {
    var a, b;

    class Add {
      addition(a, b) {
        var c;
        c = a + b;
        return console.log("Addition is: " + c);
      }

    };

    a = 1;

    b = 1;

    return Add;

  }).call(this);

  childClass = class childClass extends Add {};

  child = new childClass();

  child.addition(5, 4);

}).call(this);
