// Generated by CoffeeScript 2.1.1
(function() {
  var dynamic_range, end, i, last_position, number_range, numbers, results, retrive_data, start;

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  number_range = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20];

  console.log(number_range);

  start = 5;

  end = 15;

  dynamic_range = (function() {
    results = [];
    for (var i = start; start <= end ? i <= end : i >= end; start <= end ? i++ : i--){ results.push(i); }
    return results;
  }).apply(this);

  console.log(dynamic_range);

  retrive_data = dynamic_range.slice(0, 5);

  console.log(retrive_data);

  last_position = dynamic_range.slice(-4);

  console.log(last_position);

}).call(this);
