// Generated by CoffeeScript 2.1.1
(function() {
  var Academy;

  Academy = (function() {
    class Academy {
      static technology(name) {
        return `I want to learn ${name}`;
      }

    };

    Academy.duration = 10;

    return Academy;

  }).call(this);

  console.log(Academy.technology("Blockchain") + " in " + Academy.duration + " weeks.");

}).call(this);
