// Generated by CoffeeScript 2.1.1
(function() {
  var name, score, str1, str2, str3;

  name = 'pradeep';

  score = 30;

  console.log(`Hi ${name}, your score is ${score}.`);

  str1 = "HI";

  str2 = " Hello";

  str3 = str1.concat(str2);

  console.log(str3);

}).call(this);
